// Generated by CoffeeScript 1.6.3
(function() {
  var App;

  App = {
    helpers: {
      numFormat: function(num) {
        var numStr, rgx;
        numStr = num + '';
        rgx = /(\d+)(\d{3})/;
        while (rgx.test(numStr)) {
          numStr = numStr.replace(rgx, '$1' + ' ' + '$2');
        }
        return numStr;
      }
    },
    setInputEvents: function() {
      return $("input[type='text']").each(function() {
        var $this;
        $this = $(this);
        if (!$this.attr("data-placeholder")) {
          return;
        }
        $this.off("focus").off("blur");
        $this.on("focus", function() {
          var val;
          $this = $(this);
          val = $this.val();
          if ($.trim(val) === $this.attr("data-placeholder")) {
            $this.val("");
            $this.removeClass("blured");
          }
          return $this.removeClass("error");
        });
        $this.on("blur", function() {
          var val;
          $this = $(this);
          val = $this.val();
          if ($.trim(val) === "") {
            $this.val($this.attr("data-placeholder"));
            return $this.addClass("blured");
          }
        });
        if ($.trim($this.val()) === '') {
          return $this.blur();
        }
      });
    },
    sliderSpeed: 600,
    sliderBind: function() {
      $(".head .slider .arrow-r").on("click.slidePic", {
        wrapper: $(".head .pictures"),
        delay: 0,
        speed: 600
      }, this.slideRight);
      $(".head .slider .arrow-r").on("click.slideTextBlack", {
        wrapper: $(".head .text-black"),
        delay: 0,
        speed: 500
      }, this.slideRight);
      $(".head .slider .arrow-r").on("click.slideTextRed", {
        wrapper: $(".head .text-red"),
        delay: 0,
        speed: 700
      }, this.slideRight);
      $(".head .slider .arrow-l").on("click.slidePic", {
        wrapper: $(".head .pictures"),
        delay: 0,
        speed: 600
      }, this.slideLeft);
      $(".head .slider .arrow-l").on("click.slideTextBlack", {
        wrapper: $(".head .text-black"),
        delay: 0,
        speed: 500
      }, this.slideLeft);
      $(".head .slider .arrow-l").on("click.slideTextRed", {
        wrapper: $(".head .text-red"),
        delay: 0,
        speed: 700
      }, this.slideLeft);
      return setInterval("$('.head .slider .arrow-r').click();", 5000);
    },
    slideRight: function(e) {
      var $current, $next, $slider, $wrapper, slideWidth;
      $slider = e.data.wrapper;
      $wrapper = e.data.wrapper;
      $wrapper.stop(true, true);
      $current = $wrapper.find(".slider-item:first");
      $next = $wrapper.find(".slider-item:nth-child(2)");
      if ($current.length !== 1 || $next.length !== 1) {
        return false;
      }
      slideWidth = $slider.width();
      $current.css({
        width: slideWidth
      });
      $next.css({
        width: slideWidth
      });
      $wrapper.css({
        width: "9999px"
      });
      return $wrapper.animate({
        left: -slideWidth
      }, e.data.speed, function() {
        $wrapper = $(this).attr("style", "");
        $current = $wrapper.find(".slider-item:first").attr("style", "").appendTo($wrapper);
        return $next = $wrapper.find(".slider-item:first").attr("style", "");
      });
    },
    slideLeft: function(e) {
      var $current, $next, $slider, $wrapper, slideWidth;
      $slider = e.data.wrapper;
      $wrapper = e.data.wrapper;
      $wrapper.stop(true, true);
      $current = $wrapper.find(".slider-item:first");
      $next = $wrapper.find(".slider-item:last");
      if ($current.length !== 1 || $next.length !== 1) {
        return false;
      }
      slideWidth = $slider.width();
      $current.css({
        width: slideWidth
      });
      $next.css({
        width: slideWidth
      }).prependTo($wrapper);
      $wrapper.css({
        width: "9999px",
        left: -slideWidth
      });
      return $wrapper.animate({
        left: 0
      }, e.data.speed, function() {
        $wrapper = $(this).attr("style", "");
        $current = $wrapper.find(".slider-item:first").attr("style", "");
        return $next = $wrapper.find(".slider-item:last").attr("style", "");
      });
    }
  };

  $(document).ready(function() {
    App.sliderBind();
    App.setInputEvents();
  });

}).call(this);
